### ISSUE TITLE
How to use this library?

### ISSUE THREAD

**Issue by sobolevn** [kristerkari/stylelint-config-recommended-scss#24]
Hi, I just could not realize how to use this library.

After following the discussion in https://github.com/kristerkari/stylelint-scss/issues/91#issuecomment-315609686 I was sure that this config turns on all recommended `scss/` rules.

But as I understand from the source code https://github.com/kristerkari/stylelint-config-recommended-scss/blob/master/index.js it does not actually turn on any of the `scss/` rules. Except for one.

So, could you please clarify, how to turn on recommended scss rules?

**Comment by ntwb** [comment]
It does, the thing is though currently there is only one recommended rule, and that rule is `scss/at-rule-no-unknown` https://github.com/kristerkari/stylelint-config-recommended-scss/blob/master/index.js#L8

**Comment by sobolevn** [comment]
Oh, I get it. Why other rules are not recommended?

**Comment by kristerkari** [comment]
@sobolevn Let me explain.

This config does not turn on all the recommended `scss/*` rules, because we haven't define what those rules would be.

This config extends `stylelint-config-recommended`, which means that it turns on all the rules from that config.

The only extra thing that this config does is that it disables `at-rule-no-unknown` and turns on the SCSS syntax specific version `scss/at-rule-no-unknown`.

So this config is a replacement for `stylelint-config-recommended` when you are using Sass.

The only thing that you need is to install this config with npm and then use it by adding this to your stylelint config: `"extends": "stylelint-config-recommended-scss",`

**Comment by sobolevn** [comment]
@kristerkari thank you for the detailed explanation. 
In the mean time I have created my own configuration for `stylelint-scss`.
https://github.com/wemake-services/stylelint-config-strict-scss

Any feedback is highly appreciated!

**Comment by kristerkari** [comment]
@sobolevn Wow, that's nice! 

I'm thinking that it's better that people create their own recommended configs for`stylelint-scss` rules, as many of the rules are related to code style. :) 👍

**Comment by ntwb** [comment]
@sobolevn Quick piece of feedback, instead of https://github.com/wemake-services/stylelint-config-strict-scss/blob/master/index.js#L20-L21 you should extend `stylelint-config-recommended-scss`

**Comment by sobolevn** [comment]
Would not extending `stylelint-config-recommended-scss` conflict with `stylelint-config-standard`?

**Comment by ntwb** [comment]
@sobolevn No, `stylelint-config-recommended-scss` doesn't extend or use `stylelint-config-standard`, though I think you may have meant `stylelint-config-recommended`.

I did this in `stylelint-config-wordpress/scss` [not long ago](https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/blob/master/scss.js#L6), [here's a test](https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress/blob/d86395f40c937348457bbbafaac3040a67194aa1/__tests__/scss-invalid.scss#L25-L32) I created to ensure it does what is expected
